### ISSUE TITLE
Render markdown link

### ISSUE THREAD

**Issue by aknarts** [sgrimee/webex-tui#48]
when sending a markdown message with a link the link gets hidden. Not sure how the API returns the message here, if it strips the link from the text version of the message there is not much that can be done.

**Comment by sgrimee** [comment]
The API returns this:
```
text: Some(
        "link",
    ),
    markdown: None,
    html: Some(
        "<p><a href=\"https://google.com\" alt=\"https://google.com\" onclick=\"return sparkBase.clickEventHandler(event);\">link</a></p>",
    ),
 ```
 At the moment we are only rendering the `text`. Unfortunately the `markdown` is empty!
 We could try to parse the `html` but it feels like opening a can of works... I agree this is needed though

**Comment by aknarts** [comment]
https://crates.io/crates/html2md ?:D

**Comment by sgrimee** [comment]
I went with [html2text](https://docs.rs/html2text/latest/html2text/), seems to work fine.
I am not sure yet how to render markdown properly, apart from converting it first to html.
I have tried, and saw no big different from just displaying the markdown source, which has now been added as well.
