### ISSUE TITLE
Updated rooms should move to the top of the list

### ISSUE THREAD

**Issue by aknarts** [sgrimee/webex-tui#57]
The order of rooms currently is in the order they are loaded from the API and only way to get room to the top is to enter a new one. 

New message, sending a message and possibly other actions(entering the room to read it?) should move the room to the top of the list.

This might need to be an option or another pane on the room list.

**Comment by sgrimee** [comment]
The order should be that of last update, at least in the latest master (from last night). New incoming messages and messages sent should bring it to the top, in theory. But I have seen that fail so there is a bug in that area.
Rooms are kept sorted by last update stamp, internally. or should ne.
